# Generated by Django 4.2.9 on 2024-02-03 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_rename_mcqsubmisstion_mcqsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectiveSubmission',
            fields=[
                ('subid', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_answer', models.TextField()),
                ('ques_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subjective')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'test_id', 'ques_id')},
            },
        ),
    ]
