# Generated by Django 4.2.9 on 2024-03-02 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subjectivesubmission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('test_id', 'qtype')},
        ),
    ]
